# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '微博' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'SVProgressHUD'
pod 'pop'
pod 'FMDB'


end
