# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '表情键盘' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 表情键盘

  target '表情键盘Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '表情键盘UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'YYModel'
end
